/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.db.h2.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Greeting implements Serializable {

    private static final long serialVersionUID = -1172003348;

    private Long   id;
    private String content;

    public Greeting() {}

    public Greeting(Greeting value) {
        this.id = value.id;
        this.content = value.content;
    }

    public Greeting(
        Long   id,
        String content
    ) {
        this.id = id;
        this.content = content;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Greeting (");

        sb.append(id);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
