/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.db.h2;


import javax.annotation.Generated;

import org.jooq.example.db.h2.tables.Greeting;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.GREETING</code>.
     */
    public static final Greeting GREETING = org.jooq.example.db.h2.tables.Greeting.GREETING;
}
